import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createClient,Session} from '@supabase/supabase-js';
import {Activity,CheckCircle2,Film,LogOut,Plus,RefreshCw,ShieldCheck,Sparkles,TriangleAlert} from 'lucide-react';

const url=import.meta.env.VITE_SUPABASE_URL||'';
const key=import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const supabase=url&&key?createClient(url,key):null;
type Job={id:string;project_title:string;concept:string;scene_count:number;target_platform:string;status:string;approval_state:string;created_at:string;error_message?:string|null};
type Scene={id:string;job_id:string;scene_id:string;status:string;qc_state:string;video_url?:string|null;prompt?:string|null};
const phases=['Intake','Parse','Breakdown','Cinematography','Render','QC','Package'];
const phaseMap:Record<string,number>={queued:1,parsing:1,scene_breakdown:2,cinematography:3,scenes_ready:4,rendering:4,assembling:6,complete:7,failed:0};

export default function App(){
 const [session,setSession]=useState<Session|null>(null),[jobs,setJobs]=useState<Job[]>([]),[scenes,setScenes]=useState<Scene[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState('');
 const [form,setForm]=useState({title:'',concept:'',scenes:3,platform:'YouTube'});
 const configured=Boolean(supabase);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 async function load(){if(!supabase||!session)return;setBusy(true);const [{data:j,error},{data:s}]=await Promise.all([supabase.from('production_jobs').select('*').order('created_at',{ascending:false}),supabase.from('production_scenes').select('*').order('scene_index')]);if(error)setNotice(error.message);else{setJobs(j||[]);setScenes(s||[]);if(!selected&&j?.[0])setSelected(j[0].id)}setBusy(false)}
 useEffect(()=>{load()},[session]);
 useEffect(()=>{if(!supabase||!session)return;const channel=supabase.channel('visionweaver-live').on('postgres_changes',{event:'*',schema:'public',table:'production_jobs'},load).on('postgres_changes',{event:'*',schema:'public',table:'production_scenes'},load).subscribe();return()=>{supabase.removeChannel(channel)}},[session]);
 async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();const email=new FormData(e.currentTarget).get('email') as string;if(!supabase)return;const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});setNotice(error?.message||'Secure sign-in link sent.')}
 async function createJob(e:FormEvent){e.preventDefault();if(!supabase||!session)return;setBusy(true);const{error}=await supabase.from('production_jobs').insert({project_title:form.title.trim(),concept:form.concept.trim(),scene_count:Number(form.scenes),target_platform:form.platform,owner_id:session.user.id,approval_state:'approved',provenance:{source:'visionweaver-console',version:'6.0.0'}});setNotice(error?.message||'Production accepted. The orchestrator will advance it on the next run period.');if(!error){setForm({...form,title:'',concept:''});await load()}setBusy(false)}
 const active=jobs.find(j=>j.id===selected)||jobs[0],activeScenes=scenes.filter(s=>s.job_id===active?.id);
 const metrics=useMemo(()=>({active:jobs.filter(j=>!['complete','failed'].includes(j.status)).length,complete:jobs.filter(j=>j.status==='complete').length,failed:jobs.filter(j=>j.status==='failed').length,renders:scenes.filter(s=>s.status==='complete').length}),[jobs,scenes]);
 if(!configured)return <Shell><Empty title="Connection setup required" text="Copy .env.example to .env.local and provide the Supabase project URL and anon key. No provider secret belongs in the browser."/></Shell>;
 if(!session)return <Shell><main className="login"><div className="panel"><Sparkles/><h2>VisionWeaver Command</h2><p>Authorized production access only.</p><form onSubmit={signIn}><input name="email" type="email" placeholder="you@company.com" required/><button>Send secure link</button></form>{notice&&<small>{notice}</small>}</div></main></Shell>;
 return <Shell><header><div><p className="eyebrow">SYS-VISION-001 · PRODUCTION</p><h1>VisionWeaver Command</h1></div><div className="actions"><button className="ghost" onClick={load}><RefreshCw size={16}/>{busy?'Syncing':'Live sync'}</button><button className="ghost" onClick={()=>supabase!.auth.signOut()}><LogOut size={16}/>Sign out</button></div></header><main>
  <section className="metrics"><Metric label="Active productions" value={metrics.active} icon={<Activity/>}/><Metric label="Approved renders" value={metrics.renders} icon={<Film/>}/><Metric label="Completed" value={metrics.complete} icon={<CheckCircle2/>}/><Metric label="Exceptions" value={metrics.failed} icon={<TriangleAlert/>}/></section>
  <section className="grid"><form className="panel intake" onSubmit={createJob}><div className="sectionTitle"><Plus/><div><h2>New production</h2><p>Approved intake enters the resumable pipeline.</p></div></div><label>Project title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required maxLength={160}/></label><label>Creative concept<textarea value={form.concept} onChange={e=>setForm({...form,concept:e.target.value})} required minLength={20} maxLength={8000}/></label><div className="two"><label>Scenes<input type="number" min="1" max="20" value={form.scenes} onChange={e=>setForm({...form,scenes:Number(e.target.value)})}/></label><label>Platform<select value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}><option>YouTube</option><option>Instagram</option><option>TikTok</option><option>LinkedIn</option></select></label></div><button disabled={busy}>Approve & start production</button><p className="safe"><ShieldCheck/>Human approval, owner isolation, provenance and receipts are enforced.</p></form>
  <div className="panel queue"><div className="sectionTitle"><Film/><div><h2>Production queue</h2><p>{jobs.length} governed jobs</p></div></div><div className="jobList">{jobs.map(j=><button key={j.id} className={'job '+(active?.id===j.id?'selected':'')} onClick={()=>setSelected(j.id)}><span><b>{j.project_title}</b><small>{j.target_platform} · {j.scene_count} scenes</small></span><Status value={j.status}/></button>)}{!jobs.length&&<p className="muted">No productions yet.</p>}</div></div></section>
  {active&&<section className="panel detail"><div className="detailHead"><div><p className="eyebrow">{active.id}</p><h2>{active.project_title}</h2><p>{active.concept}</p></div><Status value={active.status}/></div><div className="pipeline">{phases.map((p,i)=><div className={(phaseMap[active.status]||0)>i?'done':active.status==='failed'?'failed':''} key={p}><span>{i+1}</span><small>{p}</small></div>)}</div><div className="sceneGrid">{activeScenes.map(s=><article key={s.id}><div><b>{s.scene_id}</b><Status value={s.status}/></div><p>{s.prompt||'Prompt preparation pending.'}</p><small>QC: {s.qc_state}</small>{s.video_url&&<a href={s.video_url} target="_blank">Open render</a>}</article>)}</div>{active.error_message&&<p className="error">{active.error_message}</p>}</section>}
  {notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 </main></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <div className="app">{children}</div>}
function Metric({label,value,icon}:{label:string,value:number,icon:React.ReactNode}){return <article className="metric"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></article>}
function Status({value}:{value:string}){return <span className={'status '+value}>{value.replaceAll('_',' ')}</span>}
function Empty({title,text}:{title:string,text:string}){return <main className="login"><div className="panel"><ShieldCheck/><h2>{title}</h2><p>{text}</p></div></main>}
