import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createClient,Session} from '@supabase/supabase-js';
import {Activity,ArrowUpRight,CheckCircle2,ClipboardCheck,Clock3,ExternalLink,Home,Inbox,Layers3,LogOut,Plus,RefreshCw,RotateCcw,ShieldCheck,Sparkles,Workflow,XCircle} from 'lucide-react';

const url=import.meta.env.VITE_SUPABASE_URL||'';
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY||'';
const supabase=url&&key?createClient(url,key):null;

type View='home'|'launch'|'active'|'review'|'returned';
type Membership={organization_id:string;role:string;status:string};
type JobStatus='requested'|'working'|'review'|'returned'|'rejected'|'failed';
type ReviewState='pending'|'approved'|'rejected'|'changes_requested';
type Job={
 id:string;organization_id:string;source_system:string;source_workspace:string;return_workspace:string;requested_by:string;title:string;
 request_payload:{instructions?:string;system_key?:string;system_name?:string}|null;assigned_agent?:string|null;orchestration_command_id?:string|null;
 status:JobStatus;result_reference?:{summary?:string;url?:string}|null;review_state:ReviewState;reviewed_by?:string|null;reviewed_at?:string|null;created_at:string;updated_at:string;
};
type SystemTarget={key:string;name:string;description:string;agent:string;url:string};

const systems:SystemTarget[]=[
 {key:'visionweaver',name:'VisionWeaver',description:'Image, video, movie and creative production workspace.',agent:'VISIONWEAVER',url:'https://master-ceo-dashboard.vercel.app/systems/visionweaver'},
 {key:'landweaver',name:'LandWeaver',description:'Property intelligence, diligence and market operations.',agent:'LANDWEAVER',url:'https://master-ceo-dashboard.vercel.app/systems/landweaver'},
 {key:'grantos',name:'GrantOS',description:'Grant discovery, requirements, drafting and funding operations.',agent:'GRANTOS',url:'https://master-ceo-dashboard.vercel.app/systems/grantos'},
 {key:'thelma',name:'T.H.E.L.M.A.',description:'Operations dispatch, agent coordination, incidents and approvals.',agent:'THELMA',url:'https://master-ceo-dashboard.vercel.app/systems/thelma'},
 {key:'cmgio',name:'CMGIO',description:'Growth, campaign intelligence, publishing and optimization.',agent:'CMGIO',url:'https://master-ceo-dashboard.vercel.app/systems/cmgio-map'},
 {key:'fabric',name:'EC Integration Fabric',description:'Connector health, governed execution, retries and authorizations.',agent:'THELMA',url:'https://master-ceo-dashboard.vercel.app/systems/integration-fabric'},
 {key:'ceo',name:'CEO Command Center',description:'Executive overview, decisions, systems, risk, usage and audit.',agent:'THELMA',url:'https://master-ceo-dashboard.vercel.app/dashboard'}
];

export default function App(){
 const[session,setSession]=useState<Session|null>(null),[membership,setMembership]=useState<Membership|null>(null),[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[view,setView]=useState<View>('home'),[selectedId,setSelectedId]=useState(''),[resultText,setResultText]=useState('');
 const[form,setForm]=useState({systemKey:'visionweaver',title:'',instructions:'',returnWorkspace:'Returned Work'});
 const configured=Boolean(supabase);

 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session){setMembership(null);setJobs([]);return}loadMembership()},[session]);
 useEffect(()=>{if(!membership)return;loadJobs()},[membership]);
 useEffect(()=>{if(!supabase||!membership)return;const channel=supabase.channel(`desktop-${membership.organization_id}`).on('postgres_changes',{event:'*',schema:'public',table:'workspace_jobs',filter:`organization_id=eq.${membership.organization_id}`},()=>loadJobs()).subscribe();return()=>{supabase.removeChannel(channel)}},[membership]);
 const selected=jobs.find(j=>j.id===selectedId)||null;
 useEffect(()=>{setResultText(selected?.result_reference?.summary||'')},[selectedId,selected?.result_reference?.summary]);

 async function loadMembership(){if(!supabase||!session)return;setBusy(true);const{data,error}=await supabase.from('ceo_organization_memberships').select('organization_id,role,status').eq('user_id',session.user.id).eq('status','active').limit(1).maybeSingle();setBusy(false);if(error)setNotice(error.message);setMembership(data||null)}
 async function loadJobs(){if(!supabase||!membership)return;setBusy(true);const{data,error}=await supabase.from('workspace_jobs').select('*').eq('organization_id',membership.organization_id).order('created_at',{ascending:false});setBusy(false);if(error)setNotice(error.message);else{const list=(data||[]) as Job[];setJobs(list);if(selectedId&&!list.some(j=>j.id===selectedId))setSelectedId('')}}
 async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const email=String(new FormData(e.currentTarget).get('email')||'').trim();const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});setNotice(error?.message||'Secure sign-in link sent.')}
 async function recordEvent(job:Job,eventType:string,fromStatus:string|null,toStatus:string|null,note:string,evidence?:Record<string,unknown>){if(!supabase||!session)return;await supabase.from('workspace_job_events').insert({organization_id:job.organization_id,job_id:job.id,event_type:eventType,from_status:fromStatus,to_status:toStatus,actor_id:session.user.id,note,evidence:evidence||{}})}
 async function launchWorkspace(e:FormEvent){e.preventDefault();if(!supabase||!session||!membership)return;const target=systems.find(s=>s.key===form.systemKey)!;setBusy(true);setNotice('');
   const{data:job,error:jobError}=await supabase.from('workspace_jobs').insert({organization_id:membership.organization_id,source_system:'SYS-DESKTOP-001',source_workspace:`systems-desktop/${target.key}`,return_workspace:form.returnWorkspace.trim()||'Returned Work',requested_by:session.user.id,title:form.title.trim(),request_payload:{instructions:form.instructions.trim(),system_key:target.key,system_name:target.name},assigned_agent:target.agent,status:'requested',review_state:'pending'}).select('*').single();
   if(jobError||!job){setBusy(false);setNotice(jobError?.message||'Could not create workspace request.');return}
   await recordEvent(job as Job,'requested',null,'requested','Request launched from Estiban Systems Desktop.',{system_key:target.key,return_workspace:form.returnWorkspace});
   const{data:command,error:commandError}=await supabase.from('orchestration_commands').insert({organization_id:membership.organization_id,requested_by:session.user.id,source_system:'SYS-DESKTOP-001',target_agent:target.agent,action_type:'workspace_request',risk_level:'medium',authorization_state:'ASK',execution_status:'queued',payload_reference:{workspace_job_id:job.id,system_key:target.key,title:form.title.trim(),instructions:form.instructions.trim(),return_workspace:form.returnWorkspace.trim()||'Returned Work'}}).select('id').single();
   if(command?.id)await supabase.from('workspace_jobs').update({orchestration_command_id:command.id,updated_at:new Date().toISOString()}).eq('id',job.id);
   setBusy(false);setForm({...form,title:'',instructions:''});setSelectedId(job.id);setView('active');await loadJobs();setNotice(commandError?'Workspace created; orchestration command needs attention.':'Workspace launched and queued for governed execution.');
 }
 async function transition(job:Job,next:JobStatus,reviewState:ReviewState=job.review_state){if(!supabase||!session)return;setBusy(true);const patch:Record<string,unknown>={status:next,review_state:reviewState,updated_at:new Date().toISOString()};if(resultText.trim())patch.result_reference={...(job.result_reference||{}),summary:resultText.trim()};if(next==='returned'||next==='rejected'){patch.reviewed_by=session.user.id;patch.reviewed_at=new Date().toISOString()}const{error}=await supabase.from('workspace_jobs').update(patch).eq('id',job.id);if(!error)await recordEvent(job,`status_${next}`,job.status,next,transitionLabel(job.status,next,reviewState),{review_state:reviewState,result_summary:resultText.trim()||null});setBusy(false);setNotice(error?.message||'Workspace updated.');if(!error){await loadJobs();if(next==='review')setView('review');if(next==='returned'||next==='rejected')setView('returned')}}
 const metrics=useMemo(()=>({active:jobs.filter(j=>j.status==='requested'||j.status==='working').length,review:jobs.filter(j=>j.status==='review').length,returned:jobs.filter(j=>j.status==='returned').length,exceptions:jobs.filter(j=>j.status==='failed'||j.status==='rejected').length}),[jobs]);
 const filtered=useMemo(()=>view==='active'?jobs.filter(j=>j.status==='requested'||j.status==='working'):view==='review'?jobs.filter(j=>j.status==='review'):view==='returned'?jobs.filter(j=>['returned','rejected','failed'].includes(j.status)):jobs,[jobs,view]);

 if(!configured)return <AuthShell><div className="auth-card"><ShieldCheck/><h1>Systems Desktop needs its Supabase connection</h1><p>Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY) in the deployment environment.</p></div></AuthShell>;
 if(!session)return <AuthShell><form className="auth-card" onSubmit={signIn}><Sparkles/><p className="eyebrow">ESTIBAN CREATIONS</p><h1>Systems Desktop</h1><p>Sign in to launch governed workspaces and receive reviewed work back here.</p><input name="email" type="email" placeholder="you@company.com" required/><button>Send secure sign-in link</button>{notice&&<small>{notice}</small>}</form></AuthShell>;
 if(!membership)return <AuthShell><div className="auth-card"><ShieldCheck/><h1>Workspace membership required</h1><p>Your account is authenticated but does not have an active Estiban organization membership.</p><button onClick={()=>supabase!.auth.signOut()}>Sign out</button></div></AuthShell>;

 return <div className="desktop-shell"><aside className="sidebar"><div className="brand"><span>EC</span><div><b>ESTIBAN</b><small>SYSTEMS DESKTOP</small></div></div><nav>
  <NavButton icon={<Home/>} label="Home" active={view==='home'} onClick={()=>{setView('home');setSelectedId('')}}/>
  <NavButton icon={<Plus/>} label="Launch a Workspace" active={view==='launch'} onClick={()=>{setView('launch');setSelectedId('')}}/>
  <NavButton icon={<Activity/>} label="Active Work" count={metrics.active} active={view==='active'} onClick={()=>{setView('active');setSelectedId('')}}/>
  <NavButton icon={<ClipboardCheck/>} label="Review" count={metrics.review} active={view==='review'} onClick={()=>{setView('review');setSelectedId('')}}/>
  <NavButton icon={<Inbox/>} label="Returned Work" count={metrics.returned} active={view==='returned'} onClick={()=>{setView('returned');setSelectedId('')}}/>
 </nav><div className="sidebar-foot"><small>{session.user.email}</small><span>{membership.role.replaceAll('_',' ')}</span><button onClick={()=>supabase!.auth.signOut()}><LogOut/> Sign out</button></div></aside>
 <main className="workspace"><header className="topbar"><div><p className="eyebrow">SYS-DESKTOP-001 · GOVERNED WORK</p><h1>{viewTitle(view)}</h1></div><div className="top-actions"><button className="ghost" onClick={loadJobs}><RefreshCw className={busy?'spin':''}/> Sync</button><span className="live"><i/>Supabase connected</span></div></header>
 <section className="content">
  {view==='home'&&<><section className="metric-grid"><Metric label="Active work" value={metrics.active}/><Metric label="Awaiting review" value={metrics.review}/><Metric label="Returned" value={metrics.returned}/><Metric label="Exceptions" value={metrics.exceptions}/></section><section className="panel"><SectionTitle title="Your systems" text="Open a system directly or launch governed work into it."/><div className="system-grid">{systems.map(s=><article className="system-card" key={s.key}><div><Layers3/><span className="status-dot"/></div><h3>{s.name}</h3><p>{s.description}</p><div><a href={s.url} target="_blank" rel="noreferrer">Open workspace <ExternalLink/></a><button onClick={()=>{setForm({...form,systemKey:s.key});setView('launch')}}>Launch work <ArrowUpRight/></button></div></article>)}</div></section></>}
  {view==='launch'&&<form className="panel launch-form" onSubmit={launchWorkspace}><SectionTitle title="Launch a Workspace" text="This creates one tracked job, one orchestration command, and one return destination."/><div className="form-grid"><label>System<select value={form.systemKey} onChange={e=>setForm({...form,systemKey:e.target.value})}>{systems.map(s=><option value={s.key} key={s.key}>{s.name}</option>)}</select></label><label>Return workspace<input value={form.returnWorkspace} onChange={e=>setForm({...form,returnWorkspace:e.target.value})} placeholder="Returned Work" required/></label></div><label>Request title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="What should be completed?" required maxLength={180}/></label><label>Instructions<textarea value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})} placeholder="Give the system the work, acceptance criteria, and any important constraints." required minLength={10}/></label><button className="primary" disabled={busy}><Workflow/> {busy?'Launching…':'Launch workspace'}</button></form>}
  {(view==='active'||view==='review'||view==='returned')&&!selected&&<section className="panel"><SectionTitle title={viewTitle(view)} text={filtered.length?`${filtered.length} tracked workspace request${filtered.length===1?'':'s'}.`:'Nothing is in this queue.'}/><div className="job-list">{filtered.map(j=><button key={j.id} className="job-row" onClick={()=>setSelectedId(j.id)}><div><b>{j.title}</b><small>{j.request_payload?.system_name||j.source_workspace} · Return: {j.return_workspace}</small></div><Status value={j.status}/><ArrowUpRight/></button>)}</div></section>}
  {selected&&<JobDetail job={selected} resultText={resultText} setResultText={setResultText} busy={busy} onBack={()=>setSelectedId('')} onTransition={transition}/>} 
 </section>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice('')}>×</button></div>}</main></div>
}

function JobDetail({job,resultText,setResultText,busy,onBack,onTransition}:{job:Job;resultText:string;setResultText:(v:string)=>void;busy:boolean;onBack:()=>void;onTransition:(j:Job,n:JobStatus,r?:ReviewState)=>void}){return <section className="panel job-detail"><button className="back" onClick={onBack}>← Back to queue</button><div className="detail-head"><div><p className="eyebrow">{job.id}</p><h2>{job.title}</h2><p>{job.request_payload?.instructions||'No instructions recorded.'}</p></div><Status value={job.status}/></div><div className="detail-grid"><article><small>System</small><b>{job.request_payload?.system_name||job.source_workspace}</b></article><article><small>Assigned agent</small><b>{job.assigned_agent||'Unassigned'}</b></article><article><small>Return workspace</small><b>{job.return_workspace}</b></article><article><small>Review state</small><b>{job.review_state.replaceAll('_',' ')}</b></article></div><label>Work result / reviewer notes<textarea value={resultText} onChange={e=>setResultText(e.target.value)} placeholder="Result summary, artifact location, reviewer notes, or returned-work instructions."/></label><div className="workflow-actions">{job.status==='requested'&&<button className="primary" disabled={busy} onClick={()=>onTransition(job,'working')}><Activity/> Start work</button>}{job.status==='working'&&<button className="primary" disabled={busy} onClick={()=>onTransition(job,'review','pending')}><ClipboardCheck/> Send to review</button>}{job.status==='review'&&<><button className="primary" disabled={busy} onClick={()=>onTransition(job,'returned','approved')}><CheckCircle2/> Approve & return</button><button className="secondary" disabled={busy} onClick={()=>onTransition(job,'working','changes_requested')}><RotateCcw/> Changes requested</button><button className="danger" disabled={busy} onClick={()=>onTransition(job,'rejected','rejected')}><XCircle/> Reject</button></>}{job.status==='returned'&&<span className="complete-note"><CheckCircle2/> Reviewed work returned to {job.return_workspace}.</span>}</div></section>}
function NavButton({icon,label,count,active,onClick}:{icon:React.ReactNode;label:string;count?:number;active:boolean;onClick:()=>void}){return <button className={active?'active':''} onClick={onClick}>{icon}<span>{label}</span>{typeof count==='number'&&count>0?<i>{count}</i>:null}</button>}
function Metric({label,value}:{label:string;value:number}){return <article className="metric"><Clock3/><div><strong>{value}</strong><small>{label}</small></div></article>}
function SectionTitle({title,text}:{title:string;text:string}){return <div className="section-title"><div><h2>{title}</h2><p>{text}</p></div></div>}
function Status({value}:{value:string}){return <span className={`status ${value}`}>{value.replaceAll('_',' ')}</span>}
function AuthShell({children}:{children:React.ReactNode}){return <main className="auth-shell">{children}</main>}
function viewTitle(v:View){return v==='home'?'Systems Desktop':v==='launch'?'Launch a Workspace':v==='active'?'Active Work':v==='review'?'Review Queue':'Returned Work'}
function transitionLabel(from:JobStatus,to:JobStatus,review:ReviewState){if(from==='review'&&to==='returned')return 'Reviewer approved the result and returned it to the requested workspace.';if(from==='review'&&to==='working')return 'Reviewer requested changes and returned the job to active work.';if(to==='review')return 'Work completed and submitted for review.';if(to==='working')return 'Work started.';if(to==='rejected')return `Reviewer rejected the result (${review}).`;return `${from} → ${to}`}
